Update github_workflow.yml
Fastlane debug

diff --git a/.github/workflows/github_workflow.yml b/.github/workflows/github_workflow.yml
--- a/.github/workflows/github_workflow.yml
+++ b/.github/workflows/github_workflow.yml
@@ -164,6 +164,12 @@ jobs:
    #         echo "Skipping TestFlight upload (missing credentials)"
    #         exit 0
    #       fi
+
+      - name: Verify Fastlane & IPA
+        run: |
+          echo "Current dir:" $(pwd)
+          ls -la fastlane/ || echo "❌ MISSING fastlane folder"
+          ls -la build/IPA/ || echo "❌ MISSING IPA"
    
       - name: Upload & Distribute to TestFlight
         env:
